apps/goods/urls.py
from django.urls import path,re_path,include
from goods.views import IndexView,DetailView,ListView
urlpatterns = [
    path("",IndexView.as_view(),name='index'),
    re_path(r'goods/(?P<goods_id>\d+)/',DetailView.as_view(),name="detail"),
    re_path(r'list/(?P<type_id>\d+)/(?P<page>\d+)',ListView.as_view(),name="list"),
    path(r'search/',include('haystack.urls')), #全文检索框架
]

apps/order/urls.py
from django.urls import path
from order.views import OrderView,CommitView
urlpatterns = [
    path(r'',OrderView.as_view(),name='order'),
    path(r'commit',CommitView.as_view(),name='commit'),
]

apps/user/urls.py
from django.urls import path,re_path
from user import views
from user.views import RegisterView,ActiveView,LoginView,UserOrderView,UserInfoView,AddressView,LogoutView,CartView
from django.contrib.auth.decorators import login_required
urlpatterns = [
    # path("register/",views.register,name='register'),#name用于url 反向解析使用
    # path('register_handle/',views.register_handle,name="register_handle"),
    path('register/',RegisterView.as_view(),name='register'),
    re_path(r'active/(?P<token>.*)$',ActiveView.as_view(),name="active"),
    path(r'login/',LoginView.as_view(),name="login"),
    path(r'order/',login_required(UserOrderView.as_view()),name='order'),
    re_path(r'info/',UserInfoView.as_view(),name="info"),
    path(r'address/',AddressView.as_view(),name="address"),
    path(r'logout/',LogoutView.as_view(),name='logout'),
    path(r'cart/',CartView.as_view(),name="cart")
]

shennxian/urls.py
from django.contrib import admin
from django.urls import path,include
import tinymce
from apps import user
urlpatterns = [
    path('admin/', admin.site.urls),
    path(r'tinymce/',include('tinymce.urls')),
    path(r'user/',include(('user.urls','user'),namespace='user')),
    path(r"order/",include(('order.urls','order'),namespace='order')),
    path(r"cart/",include(('cart.urls','cart'),namespace='cart')),
    path(r"",include(('goods.urls','goods'),namespace='goods')),
]

apps/order/models.py
from django.db import models
from db.base_model import BaseModel
# Create your models here.
class OrderInfo(BaseModel):
    PAY_METHOD_CHOICE = (
        (1,'货到付款'),
        (2,'微信支付'),
        (3,'支付宝'),
        (4,'银联支付'),
    )

    ORDER_STATUS_CHOICE = (
        (1,'待支付'),
        (2,'待发货'),
        (3,'待收货'),
        (4,'待评价'),
        (5,'已完成'),
    )

    order_id = models.CharField(max_length=128,primary_key=True,verbose_name='订单id')
    user = models.ForeignKey('user.User',verbose_name="用户",on_delete=models.CASCADE)
    addr = models.ForeignKey('user.Address',verbose_name="地址",on_delete=models.CASCADE)
    pay_method = models.SmallIntegerField(choices=PAY_METHOD_CHOICE,default=3,verbose_name="支付方式")
    total_count = models.IntegerField(default=1,verbose_name="商品数量")
    total_price = models.DecimalField(max_digits=10,decimal_places=2,verbose_name="总价")
    transit_price = models.DecimalField(max_digits=10,decimal_places=2,verbose_name="运费")
    order_status = models.SmallIntegerField(choices=ORDER_STATUS_CHOICE,verbose_name="订单状态")
    #支付方返回的编号
    trade_no = models.CharField(max_length=128,verbose_name='支付编号')

    class Meta:
        db_table = 'df_order_info'
        verbose_name = "订单信息"
        verbose_name_plural = verbose_name
class OrderGoods(BaseModel):
    order = models.ForeignKey('OrderInfo',verbose_name="订单",on_delete=models.CASCADE)
    sku = models.ForeignKey('goods.GoodsSKU',verbose_name="商品SKU",on_delete=models.CASCADE)
    count = models.IntegerField(default=1,verbose_name="商品数目")
    price = models.DecimalField(max_digits=10,decimal_places=2,verbose_name="商品价格")
    comment = models.CharField(max_length=256,verbose_name="评论")

    class Meta:
        db_table = 'df_order_goods'
        verbose_name = "订单商品"
        verbose_name_plural = verbose_name



apps/order/views.py
from django.shortcuts import render,HttpResponseRedirect as redirect
from django.urls import reverse
from django.db import transaction
from django.http import JsonResponse
# Create your views here.
from alipay import AliPay,ISVAliPay
from django.views import View
from order import models
from user import models as user_models
from goods import models as goods_models
import os
from django_redis import get_redis_connection
from django import conf
from django.db import transaction
# /order

class OrderView(View):
    def post(self,request):
        #判断用户是否登录
        print('结算')
        user = request.user
        if not user.is_authenticated:
            return redirect(reverse("user:login"))
        #获取数据

        #用户的地址信息
        try:
            user = user_models.User.objects.get(id=user.id)
            address = user_models.Address.objects.filter(user=user)
        except user_models.Address.DoesNotExist as e:
            return render(request,'order_list.html',{'res':0,"msg":"没有地址信息，请添加地址"})
        #动态添加属性
        default_address = user_models.Address.objects.get_default_address(user)
        #商品信息 sku_id,数量从redis中获取，价格从数据库中获取
        sku_ids = request.POST.get('skus')
        print(sku_ids)
        sku_id_list = sku_ids.split(',')
        try:
            skus = goods_models.GoodsSKU.objects.filter(id__in=sku_id_list)
        except goods_models.GoodsSKU.DoesNotExist as e:
            return render(request,'order.html',{"res":0,"msg":"商品不存在"})

        #计算总价格
        total_count = 0
        total_amount = 0
        cart_key = "cart_%d"%user.id
        connection = get_redis_connection('default')
        for sku in skus:
            #获取数量
            count = int(connection.hget(cart_key,sku.id))
            sku.count = count
            price = sku.price
            amount = count * price
            total_count = total_count + count
            total_amount = total_amount + amount
        # connection.hset('order_%s'%user.id,)


        context = {
            "skus": skus,
            "total_amount":total_amount,
            "total_count":total_count,
            'address':address,
            "default_address":default_address,
            'sku_ids':sku_ids,
        }
        return render(request,'order_list.html',context)

class CommitView(View):
    # @transaction.automic
    def post(self,request):
        #判断是否登录
        user = request.user
        if not user.is_authenticated:
            return JsonResponse({"res":0,"msg":"请先登录"})
        #获取信息 校验
        addr_id = request.POST.get('addr_id')
        sku_ids = request.POST.get('sku_ids')
        pay_style = request.POST.get("pay_style")
        if not all([addr_id,sku_ids,pay_style]):
            return JsonResponse({'res':0,'msg':"数据不完整"})
        #地址校验
        try:
            address = user_models.Address.objects.get(id=addr_id,user=user)
        except user_models.Address.DoesNotExist as e:
            return JsonResponse({'res': 0, 'msg': "地址信息有误"})
        #商品信息校验
        sku_id_list = sku_ids.split(',')
        print(sku_id_list)
        try:
            skus = goods_models.GoodsSKU.objects.filter(id__in=sku_id_list)
        except goods_models.GoodsSKU.DoesNotExist as e:
            return JsonResponse({'res': 0, 'msg': "商品信息有误"})

        connection = get_redis_connection('default')
        cart_key = 'cart_%s'%user.id
        import time
        time.sleep(10)
        total_count = 0
        total_amount = 0
        for sku in skus:
            #获取数量
            count = connection.hget(cart_key,sku.id)
            print(count)
            sku.count = int(count)
            price = sku.price
            amount = sku.count * price
            total_count = total_count + sku.count
            total_amount = total_amount + amount
            sku.old_stock = sku.stock
            print('old_stock',sku.old_stock)
        #创建OrderInfo对象
        from datetime import datetime
        order_id = datetime.now().strftime('%Y%m%d%H%M%S')+str(user.id)
        order = models.OrderInfo.objects.create(order_id=order_id,
                                                user=user,
                                                addr=address,
                                                pay_method=int(pay_style),
                                                total_count=total_count,
                                                total_price=total_amount,
                                                transit_price=10,
                                                order_status=1
                                                )
        #乐观锁
        #创建订单商品表
        for sku in skus:
            order_goods = models.OrderGoods.objects.create(order=order,
                                                           sku=sku,
                                                           count=sku.count,
                                                           price=sku.price,
                                                           comment=""
                                                       )
            #更新商品表的库存数据，判断和之前的库存数据是否相同
            update_goods = goods_models.GoodsSKU.objects.get(id=sku.id,stock=sku.old_stock)
            update_goods.stock = sku.old_stock - sku.count
            update_goods.sales =  update_goods.sales + sku.count
            print("用户：%s 商品id:%d 先前的库存:%d 当前的库存%d"%(user.username,sku.id,sku.old_stock,update_goods.stock))
            update_goods.save()
        #如果以上都不误，说明订单创建成功，删除购物车内对应的数据
        return JsonResponse({'res':1,'msg':"创建订单成功"})



class OrderPay(View):
    '''订单支付'''
    def post(self,request):
        #用户是否登录
        user = request.user
        #接收参数
        if not user.is_authenticated():
            return JsonResponse({'res':0,'errmsg':'用户未登录'})
        order_id = request.POST.get('order_id')
        if not order_id:
            return JsonResponse({'res':1,'errmsg':"无效的订单id"})
        try:
            #满足的条件包括 订单id 用户 支付方式 支付状态
            order = models.OrderInfo.objects.get(order_id=order_id,
                                                 user=user,
                                                 pay_method=3,
                                                 order_status=1
                                                 )
        except models.OrderInfo.DoesNotExist as e:
            return JsonResponse({'res':1,'errmsg':"订单错误"})
        #业务处理

        alipay = AliPay(
            appid="2016102200737964",
            app_notify_url=None,  # 默认回调url
            app_private_key_string=os.path.join(conf.settings.BASE_DIR,'apps/order/alipay_private_key.pem'),
            # 支付宝的公钥，验证支付宝回传消息使用，不是你自己的公钥,
            alipay_public_key_string=os.path.join(conf.settings.BASE_DIR,'apps/order/alipay_public_key.pem'),
            sign_type="RSA2",  # RSA 或者 RSA2
            debug = True  # 默认False
        )
        #调用支付接口
        order_string = alipay.api_alipay_trade_page_pay(
            out_trade_no="20161112",
            total_amount=0.01,
            subject="daydayfresh",
            return_url="",
            notify_url=""  # 可选, 不填则使用默认notify url
        )
        #返回
        pay_url = 'https://openapi.alipaydev.com/gateway.do?' + order_string
        return JsonResponse({'res':3,'pay_url':pay_url})

class CheckPayView(View):
    def post(self,request):
        # 用户是否登录
        user = request.user
        # 接收参数
        if not user.is_authenticated():
            return JsonResponse({'res': 1, 'errmsg': '用户未登录'})
        order_id = request.POST.get('order_id')
        if not order_id:
            return JsonResponse({'res': 1, 'errmsg': "无效的订单id"})
        try:
            # 满足的条件包括 订单id 用户 支付方式 支付状态
            order = models.OrderInfo.objects.get(order_id=order_id,
                                                 user=user,
                                                 pay_method=3,
                                                 order_status=1
                                                 )
        except models.OrderInfo.DoesNotExist as e:
            return JsonResponse({'res': 1, 'errmsg': "订单错误"})
        # 业务处理

        alipay = AliPay(
            appid="2016102200737964",
            app_notify_url=None,  # 默认回调url
            app_private_key_string=os.path.join(conf.settings.BASE_DIR, 'apps/order/alipay_private_key.pem'),
            # 支付宝的公钥，验证支付宝回传消息使用，不是你自己的公钥,
            alipay_public_key_string=os.path.join(conf.settings.BASE_DIR, 'apps/order/alipay_public_key.pem'),
            sign_type="RSA2",  # RSA 或者 RSA2
            debug=True  # 默认False
        )
        #调用支付宝交易查询接口
        while True:
            query = alipay.api_alipay_trade_query(out_trade_no=order_id)
            code = query.get('code')
            trade_status = query.get('trade_status')
            if code == '10000' and trade_status == "TRADE_SUCCESS":
                #支付成功
                trade_no = query.get('trade_no')
                #改变订单 状态
                order.trade_no = trade_no
                order.trade_status = '待评价'
                order.save
                # 返回结果
                return JsonResponse({'res':0,'msg':"支付成功"})
            elif code == '10000' and trade_status == "WAIT_BUYER_PAY":
                #待付款
                import time
                time.sleep(5)
                continue
            #订单超时
            else:
                return JsonResponse({'res':1,'msg':"支付失败"})







templates/address.html
{% extends 'base.html' %}
{% load staticfiles %}

	{% block title %}
        用户中心
	{% endblock title %}


    {% block topfiles %}
        <script type="text/javascript" src="/static/js/jquery-1.12.4.min.js"></script>
    {% endblock topfiles %}


{% block search_content %}
    <div class="search_bar clearfix">
		<a href="/" class="logo fl"><img src="/static/images/logo.png"></a>

            <div class="sub_page_name fl">|&nbsp;&nbsp;&nbsp;&nbsp;用户中心</div>

		<div class="search_con fl">
             <script>
                $(function () {
                    $('.input_btn').click(function () {
                        q = $('.input_text').val();
                        if(q==""){
                        alert("请输入搜索内容");
                        }
                        else{
                            location.href = '/search/?q='+q+'&page=1'
                        }
                    })
                })

            </script>
			<input type="text" class="input_text fl" name="q" placeholder="搜索商品">
			<input type="button" class="input_btn fr" name="" value="搜索">
		</div>
	</div>
{% endblock search_content %}







{% block body %}
		<div class="main_con clearfix">
		<div class="left_menu_con clearfix">
			<h3>用户中心</h3>
			<ul>
                <li><a href="{% url 'user:info' %}">· 个人信息</a></li>
				<li><a href="{% url 'user:order' %}">· 全部订单</a></li>
				<li><a href="{% url 'user:address' %}" class="active">· 收货地址</a></li>
			</ul>
		</div>
		<div class="right_content clearfix">
				<h3 class="common_title2">收货地址</h3>
				<div class="site_con">
					<dl>
                        <dt>收件人：</dt>
                        <dd>{{ address.receiver }}</dd>
                        <dt>电话：</dt>
                        <dd>{{ address.phone }}</dd>
                        <dt>当前地址：</dt>
                       <dd>{% if address %}
                           {{ address.addr }} &nbsp&nbsp{{ address.receiver }} （收）
                           {% else %}
                           {{ msg }}
                       {% endif %}</dd>
					</dl>
				</div>
				<h3 class="common_title2">编辑地址</h3>
				<div class="site_con">
					<form method="post">
                        {% csrf_token %}
						<div class="form_group">
							<label>收件人：</label>
							<input type="text" name="receiver" value="">
						</div>
                        <div class="form_group">
                            <label>手机：</label>
                            <input type="text" name="phone" value="">
                        </div>
                        <div class="form_group">
                            <label>邮编：</label>
                            <input type="text" name="zip_code" value="">
                        </div>
                        <div class="form_group form_group2">
                            <label>详细地址：</label>
                            <textarea class="site_area" name="address" ></textarea>
                        </div>
						<input type="submit" name="" value="修改地址" class="info_submit">
					</form>
				</div>
		</div>
	</div>
{% endblock body %}



{% block bottomfiles %}
{% endblock bottomfiles %}
{% block fotter %}
{% endblock fotter %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
{% load staticfiles %}
<head>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
	<meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
	<title>{% block title %}{% endblock title %}</title>
	<link rel="stylesheet" type="text/css" href="{% static "css/reset.css" %}">
	<link rel="stylesheet" type="text/css" href="{% static "css/main.css" %}">
    {% block topfile %}
    {% endblock topfile %}

</head>
<body>


{% block head-con %}

    <div class="header_con">
		<div class="header">
			<div class="welcome fl">欢迎来到天天生鲜!</div>
			<div class="fr">

                    {% if user.is_authenticated %}
                	<div class="login_btn fl">你好<em>{{ user.username }}</em>
                    <span>|</span>
                    <em><a href="{% url 'user:logout' %}">退出</a></em>
				    </div>
                    {% else %}
				<div class="login_btn fl">
					<a href="{% url 'user:login' %}">登录</a>
					<span>|</span>
					<a href="{% url 'user:register' %}">注册</a>
				</div>
                {% endif %}
				<div class="user_link fl">
					<span>|</span>
					<a href="{% url 'user:info' %}">用户中心</a>
					<span>|</span>
					<a href="{% url 'user:cart' %}">我的购物车</a>
					<span>|</span>
					<a href="{% url 'user:order' %}">我的订单</a>
				</div>
			</div>
		</div>
	</div>
{% endblock head-con %}

{% block search_content %}
    <div class="search_bar clearfix">
		<a href="/" class="logo fl"><img src="/static/images/logo.png"></a>
        
		<div class="search_con fl">
             <script>
                $(function () {
                    $('.input_btn').click(function () {
                        q = $('.input_text').val();
                        if(q==""){
                        alert("请输入搜索内容");
                        }
                        else{
                            location.href = '/search/?q='+q+'&page=1'
                        }
                    })
                })

            </script>
            <form action="/search" method="get">
                <input type="text" class="input_text fl" name="q" placeholder="搜索商品">
                <input type="submit" class="input_btn fr" name="" value="搜索">
            </form>
		</div>

        
            <div class="guest_cart fr">
                <a href="/cart/" class="cart_name fl">我的购物车</a>
                <div class="goods_count fl" id="show_count">0</div>
            </div>
        
	</div>
{% endblock search_content %}

{% block body %}{% endblock body %}

{% block bottomfiles %}{% endblock bottomfiles %}

{% block fotter %}
    <div class="footer no-mp">
		<div class="foot_link">
			<a>公司：北京乘数网络信息有限公司</a>
			<span>|</span>
			<a href="#">电话：13901184413</a>
			<span>|</span>
			<a href="http://www.chengshuwangluo.com/">联系我们</a>
			<span>地址：北京市密云区新南路69号3层兰华三层01(342)</span>
			<a href="http://beian.miit.gov.cn">京ICP备19031966号-1</a>
			<span>|</span>
			<a href="http://www.chengshuwangluo.com/flow/">入驻须知</a>
            <span>|</span>
            <a href="#">入驻协议</a>
		</div>
		<p>CopyRight © 2019 北京乘数网络信息有限公司 All Rights Reserved</p>
	</div>
{% endblock fotter %}
</body>

</html>

templates/detail.html
{% extends 'base_detail.html' %}
{% load staticfiles %}

templates/info.html
{% extends 'base.html' %}
{% load staticfiles %}

	{% block title %}
        用户中心
	{% endblock title %}


    {% block topfiles %}
        <script type="text/javascript" src="/static/js/jquery-1.12.4.min.js"></script>
    {% endblock topfiles %}


{% block search_content %}
    <div class="search_bar clearfix">
		<a href="/" class="logo fl"><img src="/static/images/logo.png"></a>

            <div class="sub_page_name fl">|&nbsp;&nbsp;&nbsp;&nbsp;用户中心</div>

		<div class="search_con fl">
             <script>
                $(function () {
                    $('.input_btn').click(function () {
                        q = $('.input_text').val();
                        if(q==""){
                        alert("请输入搜索内容");
                        }
                        else{
                            location.href = '/search/?q='+q+'&page=1'
                        }
                    })
                })

            </script>
			<input type="text" class="input_text fl" name="q" placeholder="搜索商品">
			<input type="button" class="input_btn fr" name="" value="搜索">
		</div>
	</div>
{% endblock search_content %}







{% block body %}
	<div class="main_con clearfix">
<div class="left_menu_con clearfix">
			<h3>用户中心</h3>
			<ul>
                <li><a href="{% url 'user:info' %}" class="active">· 个人信息</a></li>
				<li><a href="{% url 'user:order' %}">· 全部订单</a></li>
				<li><a href="{% url 'user:address' %}">· 收货地址</a></li>
			</ul>
		</div>
		<div class="right_content clearfix">
				<div class="info_con clearfix">
				<h3 class="common_title2">基本信息</h3>
						<ul class="user_info_list">
							<li><span>用户名：</span>{{ user.username }}</li>
							<li><span>联系方式：</span>&nbsp{{ address_obj.phone }}</li>
							<li><span>联系地址：</span>{{ address_obj.addr }}</li>
						</ul>
				</div>
            <ul>
                {% for goods in goods_list %}
                    <li>
                        <a href="{% url "goods:detail" goods.id %}"><img src="{{ goods.image.url }}"></a>
                        <h4><a href="{% url "goods:detail" goods.id %}">{{ goods.name }}</a></h4>
                        <div class="operate">
                            <span class="prize">￥{{ goods.price }}</span>
                            <span class="unit">{{ goods.unite }}</span>
                            <a href="" class="add_goods" title="加入购物车"></a>
                        </div>
                    </li>
                {% endfor %}

			</ul>
            </div>
		</div>
	</div>
{% endblock body %}




{% block fotter %}
{% endblock fotter %}

templates/login.html
{% extends 'base.html' %}
{% load staticfiles %}
    <title>{% block title %}登录{% endblock title %}</title>
    {% block topfiles %}
	<script type="text/javascript" src="{% static "js/jquery-1.12.4.min.js" %}"></script>
<script>
    $(function () {
        name_error = false;
        pwd_error = false;

        if(0==1){
            $('.user_error').html('用户名错误').show();
        }
        if(0==1){
            $('.pwd_error').html('密码错误').show();
        }
        $('.name_input').blur(function () {
            if($('.name_input').val().length=0){
                $('.user_error').html('请填写用户名').show();
                name_error = false;
            }else{
                $('.user_error').hide();
                name_error = true;
            }
        });
        $('.pass_input').blur(function () {
            if($('.pass_input').val().length=0){
                $('.pwd_error').html('请输入密码').show();
                pwd_error = false;
            }else{
                $('.pwd_error').hide();
                pwd_error = true;
            }
        })
    })
</script>
    {% endblock topfiles %}



{% block head-con %}{% endblock head-con %}
{% block search_content %}{% endblock search_content %}

{% block body %}
	<div class="login_top clearfix">
		<a href="/" class="login_logo"><img src="/static/images/logo02.png"></a>
	</div>

	<div class="login_form_bg">
		<div class="login_form_wrap clearfix">
			<div class="login_banner fl"></div>
			<div class="slogan fl">日夜兼程 · 急速送达</div>
			<div class="login_form fr">
				<div class="login_title clearfix">
					<h1>用户登录</h1>
					<a href="/user/register/">立即注册</a>
				</div>
		 		<div class="form_input">
					<form method="post">
                        {% csrf_token %}
						<input type="text" name="username" class="name_input" value="{{ username }}" placeholder="请输入用户名">
						<div class="user_error">输入错误</div>
						<input type="password" name="pwd" class="pass_input" value="" placeholder="请输入密码">

						<div class="pwd_error">输入错误</div>
						<div class="more_input clearfix">
							<input type="checkbox" name="remember" {{ checked }}>
							<label>记住用户名</label>
							<a href="#">忘记密码</a>
						</div>
						<input type="submit" name="" value="登录" class="input_submit">
					</form>
				</div>
			</div>
		</div>
	</div>
{% endblock body %}
{% block bottomfiles %}{% endblock bottomfiles %}
{% block fotter %}{% endblock fotter %}

templates/order.html
{% extends 'base.html' %}
{% extends 'base.html' %}
{% load staticfiles %}

	{% block title %}
        用户中心
	{% endblock title %}


    {% block topfiles %}
        <script type="text/javascript" src="/static/js/jquery-1.12.4.min.js"></script>
    {% endblock topfiles %}


{% block search_content %}
    <div class="search_bar clearfix">
		<a href="/" class="logo fl"><img src="/static/images/logo.png"></a>

            <div class="sub_page_name fl">|&nbsp;&nbsp;&nbsp;&nbsp;用户中心</div>

		<div class="search_con fl">
             <script>
                $(function () {
                    $('.input_btn').click(function () {
                        q = $('.input_text').val();
                        if(q==""){
                        alert("请输入搜索内容");
                        }
                        else{
                            location.href = '/search/?q='+q+'&page=1'
                        }
                    })
                })

            </script>
			<input type="text" class="input_text fl" name="q" placeholder="搜索商品">
			<input type="button" class="input_btn fr" name="" value="搜索">
		</div>
	</div>
{% endblock search_content %}







{% block body %}
	<div class="main_con clearfix">
	<div class="main_con clearfix">
<div class="left_menu_con clearfix">
			<h3>用户中心</h3>
			<ul>
                <li><a href="{% url 'user:info' %}">· 个人信息</a></li>
				<li><a href="{% url 'user:order' %}"  class="active">· 全部订单</a></li>
				<li><a href="{% url 'user:address' %}">· 收货地址</a></li>
			</ul>
		</div>
			<div class="right_content clearfix">
				<h3 class="common_title2">全部订单</h3>
				<div class="pagenation">
                            <a href="{% url 'user:order' %}" class="active">1</a>

				</div>
		</div>
	</div>
	</div>
{% endblock body %}



{% block bottomfiles %}
    <script type="text/javascript">
    $(function () {
        $('.col04').each(function () {
            count = $(this).prev().text();
            price = $(this).prev().prev().find('.good_price').text();
            $(this).html(parseFloat(count,2)*parseFloat(price,2)+'元');
            }

        )
        }
    )

    </script>
{% endblock bottomfiles %}
{% block fotter %}
{% endblock fotter %}

templates/static_index.html
{% extends 'static_base.html' %}